### ISSUE TITLE
[Suggestion] Toggle on/off push notifications in Strict Mode Notifier App

### ISSUE THREAD

**Issue by sebastian-uriel-flores** [nshmura/strictmode-notifier#5]
Hi.
I am working with your library. It´s really good. 
But sometimes, I want to test some things and I receive a lot of push notifications of Strict Mode Violations, and maybe I just want to disable them temporarily to test other things, and then, re enable it.
So, I would just suggest to add a Toggle button in the Strict Mode notifier app, to disable or enable it without having to stop and restart debugging every time I want to toggle it.

**Comment by nshmura** [comment]
Hi @fseba 
Thank you for your suggestion!
I'll consider that toggle button.

**Comment by nshmura** [comment]
@fseba Switch for Notification was added.
Please check version `0.9.3`.

<img width="310" alt="2016-08-13 14 12 18" src="https://cloud.githubusercontent.com/assets/9046837/17641614/441b76ba-6162-11e6-92ec-7d7a853d7eed.png">
